# Generated by Django 3.0.4 on 2020-05-06 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='d01time',
            name='dateRegister',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
        migrations.AlterField(
            model_name='d01time',
            name='timeRegister',
            field=models.TimeField(),
        ),
    ]
