# Generated by Django 3.0.4 on 2020-05-10 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200506_1309'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='c01Register',
            new_name='c01Employee',
        ),
    ]
