# Generated by Django 3.0.4 on 2020-05-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200510_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='b02TypeContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('durationLunch', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
