# Generated by Django 3.0.4 on 2020-05-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_b02typecontract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b02typecontract',
            name='durationLunch',
            field=models.TimeField(),
        ),
    ]
