# Generated by Django 3.0.4 on 2020-05-12 13:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200511_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='d01Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initalDate', models.DateField(default=datetime.date(2000, 1, 1))),
                ('finalDate', models.DateField(default=datetime.date(2000, 1, 1))),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.c01Employee')),
                ('typeContract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.b02TypeContract')),
            ],
        ),
        migrations.CreateModel(
            name='d02Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateRegister', models.DateField(default=datetime.date(2000, 1, 1))),
                ('timeRegister', models.TimeField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.d01Report')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.b01Schedule')),
            ],
        ),
        migrations.DeleteModel(
            name='d01Time',
        ),
    ]
