# Generated by Django 3.0.4 on 2020-05-12 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200512_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='d01report',
            old_name='initalDate',
            new_name='initialDate',
        ),
    ]
