# Generated by Django 3.0.4 on 2020-05-15 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200512_1051'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='d02Time',
            new_name='d02DetailsReport',
        ),
    ]
