# Generated by Django 3.0.4 on 2020-05-17 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200515_1141'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='d02DetailsReport',
            new_name='d02TimesReport',
        ),
        migrations.AlterField(
            model_name='d01report',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='main.c01Employee'),
        ),
        migrations.AlterField(
            model_name='d01report',
            name='typeContract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='typeContract', to='main.b02TypeContract'),
        ),
    ]
