# Generated by Django 3.0.4 on 2020-05-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200517_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c01employee',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
