# Generated by Django 3.0.7 on 2020-08-01 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200707_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='function',
        ),
        migrations.DeleteModel(
            name='FunctionEmployee',
        ),
    ]
