# Generated by Django 3.0.7 on 2020-08-29 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0015_auto_20200823_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typecontract',
            name='durationLunch',
        ),
        migrations.AddField(
            model_name='typecontract',
            name='hoursFriday',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='typecontract',
            name='hoursMonday',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='typecontract',
            name='hoursSaturday',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='typecontract',
            name='hoursSunday',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='typecontract',
            name='hoursThursday',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='typecontract',
            name='hoursTuesday',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='typecontract',
            name='hoursWednesday',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='typecontract',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='typeContract', to=settings.AUTH_USER_MODEL),
        ),
    ]
