# Generated by Django 3.0.7 on 2020-08-31 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20200829_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesreport',
            name='schedule',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
